# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b2751ffbaab9588f04cf607cd309423efcf99a6695aaec612bef3a2bce86a4db72428ad20763f58a5beb843c2638c88f625fcdacab194ee547c571a6a470463b

test:
  secret_key_base: c95d750de6bebc4bb3681fef40960e5732b653752c27c7a18152dcf0a92b88d59467c81d9f0a0ad3d1db51f3ebb5dbe120381a7296e19f9ba02af9bc40818d18

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
